# Generated by Django 6.0.6 on 2026-08-31 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_photo_field'),
        ('main', '0004_classe_cours_couleur_cours_creneau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='photo',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='main.classe'),
        ),
    ]
