# Generated by Django 6.0.6 on 2026-08-31 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 3ème Année - Informatique et Réseau (3-IIR)', max_length=200)),
                ('niveau', models.CharField(choices=[('1AP', '1ère Année Primaire'), ('2AP', '2ème Année Primaire'), ('3AP', '3ème Année Primaire'), ('4AP', '4ème Année Primaire'), ('5AP', '5ème Année Primaire'), ('6AP', '6ème Année Primaire'), ('1AC', '1ère Année Collège'), ('2AC', '2ème Année Collège'), ('3AC', '3ème Année Collège'), ('TCS', 'Tronc Commun Sciences'), ('1BAC_SE', '1ère Bac Sciences Expérimentales'), ('1BAC_SM', '1ère Bac Sciences Mathématiques'), ('2BAC_SE', '2ème Bac Sciences Expérimentales'), ('2BAC_SM', '2ème Bac Sciences Mathématiques')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='couleur',
            field=models.CharField(choices=[('#4a90e2', 'Bleu'), ('#50e3c2', 'Turquoise'), ('#b8e986', 'Vert clair'), ('#f5a623', 'Orange'), ('#e74c3c', 'Rouge'), ('#9b59b6', 'Violet'), ('#34495e', 'Bleu marine'), ('#1abc9c', 'Émeraude')], default='#4a90e2', max_length=20),
        ),
        migrations.AddField(
            model_name='cours',
            name='creneau',
            field=models.CharField(choices=[('08:30-10:20', '08:30 - 10:20'), ('10:30-12:20', '10:30 - 12:20'), ('14:30-16:20', '14:30 - 16:20'), ('16:30-18:20', '16:30 - 18:20')], default='08:30-10:20', max_length=20),
        ),
        migrations.AlterField(
            model_name='cours',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='main.classe'),
        ),
    ]
