# Generated by Django 6.0.6 on 2026-08-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_classe_cours_couleur_cours_creneau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans l'emploi du temps")),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['ordre', 'heure_debut'],
            },
        ),
    ]
