# Generated by Django 6.0.6 on 2026-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_creneauhoraire'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Détermine si le professeur est actif dans l'établissement."),
        ),
    ]
