# Generated by Django 6.0.6 on 2026-08-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_professeur_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='date_exacte',
            field=models.DateField(blank=True, null=True, verbose_name='Date exacte (Optionnel)'),
        ),
    ]
