# Generated by Django 6.0.6 on 2026-09-01 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cours_date_exacte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('cours', 'Cours'), ('examen', 'Examen')], default='cours', max_length=20)),
                ('fichier', models.FileField(upload_to='documents_pdf/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classes_autorisees', models.ManyToManyField(blank=True, related_name='documents_autorises', to='main.classe')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='main.cours')),
                ('etudiants_autorises', models.ManyToManyField(blank=True, related_name='documents_autorises', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='main.examen')),
            ],
            options={
                'verbose_name': 'Document Partagé',
                'verbose_name_plural': 'Documents Partagés',
                'ordering': ['-date_creation'],
            },
        ),
    ]
