# Generated by Django 6.0.6 on 2026-09-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_documentpartage'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpartage',
            name='professeurs_autorises',
            field=models.ManyToManyField(blank=True, related_name='documents_autorises', to='main.professeur'),
        ),
    ]
